# Complete list of all available properties: https://docs.upsun.com/create-apps/app-reference.html
applications:
  repair-directory:
    # Application source code directory
    source:
      root: "\"

    # The runtime the application uses.
    # Complete list of available runtimes: https://docs.upsun.com/create-apps/app-reference.html#types
    type: "php:8.2"

    # Choose which container profile (ratio CPU+RAM) your app will use. Default value comes from the image itself.
    # More information: https://docs.upsun.com/manage-resources/adjust-resources.html#adjust-a-container-profile
    # container_profile:

    # The relationships of the application with services or other applications.
    # The left-hand side is the name of the relationship as it will be exposed
    # to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
    # side is in the form `<service name>:<endpoint name>`.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#relationships
    relationships:
      mysql:
        service: "mysql"
        endpoint: "mysql:mysql"
      

    # Mounts define directories that are writable after the build is complete.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#mounts
    mounts:
      'public/uploads':
        source: local
        source_path: uploads
      # Laravel uses a directory off the root called "storage" for logs and cache.
      # We don't support specifying nested directories so make these directories
      # flat beyond "shared:files"
      "/storage/app/public": "shared:files/app-public"
      "/storage/framework/views": "shared:files/framework-views"
      "/storage/framework/sessions": "shared:files/framework-sessions"
      "/storage/framework/cache": "shared:files/framework-cache"
      "/storage/logs": "shared:files/logs"
      # And another cache directory here.
      "/bootstrap/cache": "shared:files/bootstrap_cache"

    # The web key configures the web server running in front of your app.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#web
    web:
      # Commands are run once after deployment to start the application process.
      # More information: https://docs.upsun.com/create-apps/app-reference.html#web-commands
      # commands:
        # The command to launch your app. If it terminates, it’s restarted immediately.
      #   You can use the $PORT or the $SOCKET environment variable depending on the socket family of your upstream
      #   PHP applications run PHP-fpm by default
      #   Read about alternative commands here: https://docs.upsun.com/languages/php.html#alternate-start-commands
      #   start: echo 'Put your start command here'
      # You can listen to a UNIX socket (unix) or a TCP port (tcp, default).
      # For PHP, the defaults are configured for PHP-FPM and shouldn't need adjustment.
      # Whether your app should speak to the webserver via TCP or Unix socket. Defaults to tcp
      # More information: https://docs.upsun.com/create-apps/app-reference.html#where-to-listen
      # upstream:
      #  socket_family: unix
      # Each key in locations is a path on your site with a leading /.
      # More information: https://docs.upsun.com/create-apps/app-reference.html#locations
      locations:
        "/":
          passthru: "/index.php"
          root: "public"
          
        

    # Alternate copies of the application to run as background processes.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#workers
    # workers:

    # The timezone for crons to run. Format: a TZ database name. Defaults to UTC, which is the timezone used for all logs
    # no matter the value here. More information: https://docs.upsun.com/create-apps/timezone.html
    # timezone: <time-zone>

    # Access control for roles accessing app environments.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#access
    # access:

    # Variables to control the environment. More information: https://docs.upsun.com/create-apps/app-reference.html#variables
    variables:
      env:
        N_PREFIX: "/app/.global"
      php:
        extension: /app/xmlrpc.so

    # Outbound firewall rules for the application. More information: https://docs.upsun.com/create-apps/app-reference.html#firewall
    # firewall:

    # Specifies a default set of build tasks to run. Flavors are language-specific.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#build
    build:
      flavor: none

    # Installs global dependencies as part of the build process. They’re independent of your app’s dependencies and
    # are available in the PATH during the build process and in the runtime environment. They’re installed before
    # the build hook runs using a package manager for the language.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#dependencies
    dependencies:
      nodejs:
        n: "*"
        npx: "*"
        yarn: "^1.22.0"
      php:
        composer/composer: "^2"

    # Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
    # More information: https://docs.upsun.com/create-apps/app-reference.html#hooks
    hooks:
      # The build hook is run after any build flavor.
      # More information: https://docs.upsun.com/create-apps/hooks/hooks-comparison.html#build-hook
      build: |
        echo "Executing our build process"
        set -e
        mkdir env
        cp .env.example .env
        
        # The database config depends on the platform.sh setup.
        sed -i 's/DB_DATABASE=.*$/DB_DATABASE=main/g' .env
        sed -i 's/DB_USERNAME=.*$/DB_USERNAME=root/g' .env
        sed -i 's/DB_PASSWORD=.*$/DB_PASSWORD=/g' .env
        sed -i "s/MAIL_MAILER=.*\$/MAIL_MAILER=mailgun/g" .env
        sed -i "s/SESSION_DOMAIN=.*\$/SESSION_DOMAIN=.restarters.net/g" .env
        
        # Some config is configured in platform.sh environment variables, which we can extract here to put in the
        # .env file for the code to pick up.
        sed -i "s/APP_NAME=.*\$/APP_NAME=\"$APP_NAME\"/g" .env
        sed -i "s/MAIL_FROM_ADDRESS=.*\$/MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS/g" .env
        sed -i "s/MAIL_FROM_NAME=.*\$/MAIL_FROM_NAME=\"$MAIL_FROM_NAME\"/g" .env
        sed -i "s/GA_TRACKING_ID=.*\$/GA_TRACKING_ID=$GA_TRACKING_ID/g" .env
        sed -i "s/GOOGLE_MAPS_API_KEY=.*\$/GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY/g" .env
        sed -i "s/GRAVITYFORMS_KEY=.*\$/GRAVITYFORMS_KEY=$GRAVITYFORMS_KEY/g" .env
        sed -i "s/GRAVITYFORMS_SECRET=.*\$/GRAVITYFORMS_SECRET=$GRAVITYFORMS_SECRET/g" .env
        sed -i "s/GRAVITYFORMS_SUBMISSION_FORM_ID=.*\$/GRAVITYFORMS_SUBMISSION_FORM_ID=$GRAVITYFORMS_SUBMISSION_FORM_ID/g" .env
        sed -i "s/MAP_SHARE_BASE_URL=.*\$/MAP_SHARE_BASE_URL=https:\/\/$MAP_SHARE_BASE_URL/g" .env
        
        echo "MAILGUN_DOMAIN=$MAILGUN_DOMAIN" >> .env
        echo "MAILGUN_SECRET=$MAILGUN_SECRET" >> .env
        
        cp fixometer/config/config.dist.php fixometer/config/config.php
        composer install -n
        npm install
        export NODE_OPTIONS=--max-old-space-size=8192;  npm rebuild node-sass; npm run prod
        echo "Our build process is complete"
        
      # The deploy hook is run after the app container has been started, but before it has started accepting requests.
      # More information: https://docs.upsun.com/create-apps/hooks/hooks-comparison.html#deploy-hook
      deploy: |
        set -eux
        mkdir -p storage/framework/sessions
        mkdir -p storage/framework/cache
        mkdir -p storage/framework/views
        php artisan optimize:clear
        php artisan config:clear
        php artisan doctrine:migrations:migrate
        echo "Migrated"        

      # The post_deploy hook is run after the app container has been started and after it has started accepting requests.
      # More information: https://docs.upsun.com/create-apps/hooks/hooks-comparison.html#deploy-hook
      # post_deploy: |

    # Scheduled tasks for the app.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#crons
    crons:
      # Run Laravel's scheduler every 5 minutes.
      scheduler:
        spec: '*/1 * * * *'
        cmd: 'php artisan schedule:run > /tmp/schedule.out 2>&1'

    # Customizations to your PHP or Lisp runtime. More information: https://docs.upsun.com/create-apps/app-reference.html#runtime
    # runtime:

    # More information: https://docs.upsun.com/create-apps/app-reference.html#additional-hosts
    # additional_hosts:

# The services of the project.
#
# Each service listed will be deployed
# to power your Upsun project.
# More information: https://docs.upsun.com/add-services.html
# Full list of available services: https://docs.upsun.com/add-services.html#available-services
services:
  mysql:
    type: oracle-mysql:5.7

# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Upsun.
# More information: https://docs.upsun.com/define-routes.html
routes:
  "https://{default}/":
    type: upstream
    upstream: "repair-directory:http"
  # A basic redirect definition
  # More information: https://docs.upsun.com/define-routes.html#basic-redirect-definition
  "https://www.{default}":
    type: redirect
    to: "https://{default}/"
