version: '2'

services:

  xdebug:
    depends_on:
    - database_testing
    - mail.restart-project.local
    environment:
      - APP_ENV=testing
      - DB_HOST=database_testing
      - FIXOMETER_DB_HOST=database_testing
      - APP_URL=http://test.restart-project.local

  php:
    depends_on:
    - database_testing
    - mail.restart-project.local
    environment:
      - APP_ENV=testing
      - DB_HOST=database_testing
      - FIXOMETER_DB_HOST=database_testing
      - APP_URL=http://test.restart-project.local


  composer:
    depends_on:
    - database_testing
    - mail.restart-project.local
    environment:
      - APP_ENV=testing
      - DB_HOST=database_testing
      - FIXOMETER_DB_HOST=database_testing
      - APP_URL=http://test.restart-project.local

networks:
  proxy-tier:
    external:
      name: reverse-proxy
  restartproject: