version: '2'

services:

  database:
    image: postgres:9-alpine
    container_name: restartproject_database
#    volumes:
#      - ./database:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=restartproject
      - POSTGRES_USER=restartproject
      - POSTGRES_PASSWORD=restartproject
      - PGDATA=/var/lib/postgresql/data/dev/pgdata
    networks:
      - proxy-tier
    restart: always

  phppgadmin:
    image: zhajor/docker-phppgadmin
    container_name: restartproject_phppgadmin
    environment:
      - VIRTUAL_HOST=db.restart-project.local
      - LETSENCRYPT_HOST=db.restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
      - DB_HOST=database
      - DB_PORT=5432
    networks:
      - proxy-tier
    restart: always

  # local dev email server
  maildev:
    image: djfarrelly/maildev:1.0.0-rc2
    container_name: restartproject_maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    environment:
      - VIRTUAL_HOST=mail.restart-project.local
      - LETSENCRYPT_HOST=mail.restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
    networks:
      - proxy-tier

  web:
    depends_on:
      - database
      - maildev
    build: ./php
    image: restartproject_php
    container_name: restartproject_web
    volumes:
      - ../:/app
    env_file:
      - ./php/application.env
    environment:
      - VIRTUAL_HOST=restart-project.local
      - LETSENCRYPT_HOST=restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
    command: ["php", "-S", "0.0.0.0:80", "-t", "/app", "server.php"]
    networks:
      - proxy-tier
    restart: always

  php:
    depends_on:
      - database
      - maildev
    build: ./php
    image: restartproject_php
    container_name: restartproject_php
    volumes:
      - ../:/app
    env_file:
      - ./php/application.env
    command: ["--version"]
    networks:
      - proxy-tier

  composer:
    depends_on:
      - database
      - maildev
    build: ./composer
    image: restartproject_composer
    container_name: restartproject_composer
    volumes:
      - ../:/app
    env_file:
      - ./php/application.env
    command: ["install"]
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: reverse-proxy