version: '2'

services:

  xdebug:
    environment:
      - APP_ENV=testing
      - DB_HOST=database_testing
      - APP_URL=http://test.restart-project.local

  php:
    environment:
      - APP_ENV=testing
      - DB_HOST=database_testing
      - APP_URL=http://test.restart-project.local


  composer:
    environment:
      - APP_ENV=testing
      - DB_HOST=database_testing
      - APP_URL=http://test.restart-project.local

networks:
  proxy-tier:
    external:
      name: reverse-proxy
  restartproject: