version: '2'

services:

  ############################
  ######## Databases #########
  ############################
  database:
    image: mysql:5.7
    volumes:
      - ./database/default/local:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=restartproject
      - MYSQL_DATABASE=restartproject
      - MYSQL_USER=restartproject
      - MYSQL_PASSWORD=restartproject
    networks:
      - restartproject
    restart: always

  database_testing:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=restartproject
      - MYSQL_DATABASE=restartproject
      - MYSQL_USER=restartproject
      - MYSQL_PASSWORD=restartproject
    volumes:
      - ./database/default/testing:/var/lib/mysql
    networks:
      - restartproject
    restart: always

  db.restart-project.local:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=restartproject
      - MYSQL_USER=restartproject
      - MYSQL_PASSWORD=restartproject
      - PMA_HOSTS=database,fixometer_db,database_testing
      - VIRTUAL_HOST=db.restart-project.local
    networks:
      - proxy-tier
      - restartproject
    restart: always

  ############################
  ####### Email Server #######
  ############################

  mail.restart-project.local:
    image: djfarrelly/maildev:1.0.0-rc2
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    environment:
      - VIRTUAL_HOST=mail.restart-project.local
      - LETSENCRYPT_HOST=mail.restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
    networks:
      - proxy-tier
      - restartproject
    restart: always

  ############################
  ######### Reports ##########
  ############################

  cc.restart-project.local:
    image: nginx
    volumes:
      - ../reports/codecoverage:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=cc.restart-project.local
      - LETSENCRYPT_HOST=cc.restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
      - NGINX_HOST=cc.restart-project.local
      - NGINX_PORT=80
    networks:
      - proxy-tier
    restart: always

  docs.restart-project.local:
    image: nginx
    volumes:
      - ../reports/docs:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=docs.restart-project.local
      - LETSENCRYPT_HOST=docs.restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
      - NGINX_HOST=docs.restart-project.local
      - NGINX_PORT=80
    networks:
      - proxy-tier
    restart: always

  ############################
  ####### Web Servers ########
  ############################

  restart-project.local:
    depends_on:
      - database
      - mail.restart-project.local
    build: ./php
    image: restartproject_php
    volumes:
      - ../:/app
    working_dir: "/app/public"
    env_file:
      - ./php/application.env
    environment:
      - VIRTUAL_HOST=restart-project.local
      - LETSENCRYPT_HOST=restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
    command: ["php", "-S", "0.0.0.0:80", "server.php"]
    networks:
      - proxy-tier
      - restartproject
    restart: always

  test.restart-project.local:
    depends_on:
      - database_testing
      - mail.restart-project.local
    build: ./php
    image: restartproject_php
    volumes:
      - ../:/app
    working_dir: "/app/public"
    env_file:
      - ./php/application.env
    environment:
      - APP_ENV=testing
      - DB_HOST=database_testing
      - FIXOMETER_DB_HOST=database_testing
      - APP_URL=http://test.restart-project.local
      - VIRTUAL_HOST=test.restart-project.local
      - LETSENCRYPT_HOST=restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
    command: ["php", "-S", "0.0.0.0:80", "server.php"]
    networks:
      - proxy-tier
      - restartproject
    restart: always

  ############################
  ########## Tools ###########
  ############################

  php:
    depends_on:
      - database
      - mail.restart-project.local
    build: ./php
    image: restartproject_php
    volumes:
      - ../:/app
    env_file:
      - ./php/application.env
    command: ["--version"]
    networks:
      - restartproject

  node:
    build: ./node
    image: restartproject_node
    volumes:
      - ../:/app
    command: ["node", "--version"]
    networks:
      - restartproject

  xdebug:
    depends_on:
      - database
      - mail.restart-project.local
    build: ./xdebug
    image: restartproject_xdebug
    working_dir: /app
    volumes:
      - ../:/app
    env_file:
      - ./php/application.env
    environment:
      - XDEBUG_CONFIG="idekey=PHPSTORM"
    command: ["php", "--version"]
    networks:
      - restartproject

  composer:
    depends_on:
      - database
      - mail.restart-project.local
    build: ./composer
    image: restartproject_composer
    volumes:
      - ../:/app
    env_file:
      - ./php/application.env
    command: ["install"]
    networks:
      - restartproject

  selenium:
    image: selenium/standalone-chrome
    networks:
      - restartproject

  dusk:
    depends_on:
      - database_testing
      - test.restart-project.local
      - selenium
      - mail.restart-project.local
    build: ./php
    image: restartproject_php
    volumes:
      - ../:/app
    env_file: php/application.env
    environment:
      - APP_ENV=testing
      - DB_HOST=database_testing
      - FIXOMETER_DB_HOST=database_testing
      - APP_URL=http://test.restart-project.local
    command: ["php", "artisan", "dusk"]
    networks:
      - restartproject

networks:
  proxy-tier:
    external:
      name: reverse-proxy
  restartproject: