version: '2'

services:

  database:
    environment:
      - PGDATA=/var/lib/postgresql/data/dusk/pgdata

  restart-project.local:
    environment:
      - APP_ENV=testing

  selenium:
    image: selenium/standalone-chrome
    container_name: restartproject_selenium
    networks:
      - restartproject

  php:
    environment:
      - APP_ENV=testing

  dusk:
    depends_on:
      - database
      - restart-project.local
      - selenium
      - mail.restart-project.local
    build: ./php
    image: restartproject_php
    container_name: restartproject_php
    volumes:
      - ../:/app
    env_file: php/application.env
    environment:
      - APP_ENV=testing
    command: ["php", "artisan", "dusk"]
    networks:
      - restartproject

  composer:
    environment:
      - APP_ENV=testing

networks:
  proxy-tier:
    external:
      name: reverse-proxy
  restartproject: