version: '2'

services:

  database:
    image: mariadb
    container_name: restartproject_database
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=restartproject
      - MYSQL_DATABASE=restartproject
      - MYSQL_USER=restartproject
      - MYSQL_PASSWORD=restartproject
    networks:
      - restartproject
    restart: always

  db.restart-project.local:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin:latest
    container_name: restartproject_phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=restartproject
      - MYSQL_USER=restartproject
      - MYSQL_PASSWORD=restartproject
      - PMA_HOSTS=database
      - VIRTUAL_HOST=db.restart-project.local
    networks:
      - proxy-tier
      - restartproject
    restart: always

  # local dev email server
  mail.restart-project.local:
    image: djfarrelly/maildev:1.0.0-rc2
    container_name: restartproject_maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    environment:
      - VIRTUAL_HOST=mail.restart-project.local
      - LETSENCRYPT_HOST=mail.restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
    networks:
      - proxy-tier
      - restartproject
    restart: always

  cc.restart-project.local:
    image: nginx
    container_name: restartproject_codecoverage
    volumes:
      - ../reports/codecoverage:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=cc.restart-project.local
      - LETSENCRYPT_HOST=cc.restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
      - NGINX_HOST=cc.restart-project.local
      - NGINX_PORT=80
    networks:
      - proxy-tier
    restart: always

  docs.restart-project.local:
    image: nginx
    container_name: restartproject_docs
    volumes:
      - ../reports/docs:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=docs.restart-project.local
      - LETSENCRYPT_HOST=docs.restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
      - NGINX_HOST=docs.restart-project.local
      - NGINX_PORT=80
    networks:
      - proxy-tier
    restart: always

  restart-project.local:
    depends_on:
      - database
      - mail.restart-project.local
    build: ./php
    image: restartproject_php
    container_name: restartproject_web
    volumes:
      - ../:/app
    env_file:
      - ./php/application.env
    environment:
      - VIRTUAL_HOST=restart-project.local
      - LETSENCRYPT_HOST=restart-project.local
      - LETSENCRYPT_EMAIL=admin@restart-project.local
    command: ["php", "-S", "0.0.0.0:80", "server.php"]
    networks:
      - proxy-tier
      - restartproject
    restart: always

  php:
    depends_on:
      - database
      - mail.restart-project.local
    build: ./php
    image: restartproject_php
    container_name: restartproject_php
    volumes:
      - ../:/app
    env_file:
      - ./php/application.env
    command: ["--version"]
    networks:
      - restartproject

  node:
    build: ./node
    image: restartproject_node
    container_name: restartproject_node
    volumes:
      - ../:/app
    command: ["node", "--version"]
    networks:
      - restartproject

  xdebug:
    depends_on:
      - database
      - mail.restart-project.local
    build: ./xdebug
    image: restartproject_xdebug
    container_name: restartproject_xdebug
    working_dir: /app
    volumes:
      - ../:/app
    environment:
      - XDEBUG_CONFIG="idekey=PHPSTORM"
    command: ["php", "--version"]
    networks:
      - restartproject

  composer:
    depends_on:
      - database
      - mail.restart-project.local
    build: ./composer
    image: restartproject_composer
    container_name: restartproject_composer
    volumes:
      - ../:/app
    env_file:
      - ./php/application.env
    command: ["install"]
    networks:
      - restartproject

networks:
  proxy-tier:
    external:
      name: reverse-proxy
  restartproject: